name: Update Recent Activity

on:
  schedule:
    - cron: "0 * * * *" # updates every hour
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
